version: '3.8'
# docker-compose up && docker-compose rm -fsv # run and remove on exit
# kafka-topics.sh --describe --bootstrap-server localhost:9092 --topic items # Describe topic
# kafka-topics.sh --alter --bootstrap-server localhost:9092 --topic items --partitions 2 # Create new partition under existing topic
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: "zookeeper"
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: "kafka"
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

